### ISSUE TITLE
Packages registered but not on disk

### ISSUE THREAD

**Issue by sposs** [mvantellingen/localshop#116]
I've had a few issues with localshop (installed a couple of weeks ago), where I would upload a packages but when accessing it it would not be available on disk. The issue is that localshop says it's 'local', and the path is defined but the file is missing (and I get a Http error 500). Any idea where that can come from? Even better, what can I do to avoid that problem?

The HTTP error 500 Internal server error isn't very nice as it doesn't say what the problem actually is... Maybe localshop could check if a file is actually on disk before attempting to return it. If it isn't, it could show an error, and update the DB, removing the 'local' flag for example...

Thanks.

**Comment by canassa** [comment]
I also had this problem. My guess is that this is caused by some racing condition on the workers but I haven't investigate further.

Anyway, with the fix I just submitted, localshop will re-download the file if its missing, just like it would if the package is not local.

**Comment by sposs** [comment]
Thanks!
