### ISSUE TITLE
localshop returns 404 when uploading packages

### ISSUE THREAD

**Issue by fly** [mvantellingen/localshop#121]
When trying to upload packages to localshop (running the celery worker via `localshop celery worker -B -E` and gunicorn via `localshop run_gunicorn`), I am able to successfully register a package but get a 404 when uploading the package. I can get a 200 by hitting `/simple/` with a `GET` request.
```
> python2 setup.py register -r test
...
Registering test to http://127.0.0.1:8000/simple/
Server response (200): OK
> python2 setup.py sdist upload -r test
....
running upload
Submitting dist/test-1.3.tar.gz to http://127.0.0.1:8000/simple/
Upload failed (404): NOT FOUND
error: Upload failed (404): NOT FOUND
```

I tried this on `0.4.1`, `0.5.0`, the `develop` branch, and the `master` branch.

With debug logging enabled, I get this:

```
WARNING 2015-01-14 01:50:46,260 csrf 1552 139971359459072 Forbidden (CSRF cookie not set.): /simple/
```

**Comment by canassa** [comment]
Hi, 

I fixed a similar bug a few days ago, see #117 

The fix was merged on develop its still not released. Are you sure you tested with the develop branch?

If you can confirm that this bug is still happening, I will need more information in order to reproduce and fix it.

Thanks,

**Comment by fly** [comment]
so, I may have screwed up my virtualenv, so I probably lied about testing `develop`. I cleared it up, and uploading seems to do the needful in `develop`. However, running `localshop run_gunicorn` doesn't work; it exits immediately with exit code 3, while `localshop runserver` works.

```
(localshop)localshop@localshop:/opt/virtualenvs/localshop/lib/python2.7/site-packages/localshop$ localshop run_gunicorn --debug --log-level debug
!!!
!!! WARNING: This command is deprecated.
!!!
!!!         You should now run your application with the WSGI interface
!!!         installed with your project. Ex.:
!!!
!!!             gunicorn myproject.wsgi:application
!!!
!!!         See https://docs.djangoproject.com/en/1.5/howto/deployment/wsgi/gunicorn/
!!!         for more info.
!!!

(localshop)localshop@localshop:/opt/virtualenvs/localshop/lib/python2.7/site-packages/localshop$ echo $?
3
(localshop)localshop@localshop:/opt/virtualenvs/localshop/lib/python2.7/site-packages/localshop$
```

This is on a clean installation of localshop after running `localshop init`.

**Comment by canassa** [comment]
Try running this instead of `localshop run_guinicorn`:

```
gunicorn localshop.wsgi:application --debug --log-level debug
```

The develop branch was upgraded to Django 1.7 which deprecated that command, I need to update the README accordingly.

**Comment by fly** [comment]
thanks.

updated in #122
