### ISSUE TITLE
source distributions not getting cached

### ISSUE THREAD

**Issue by fly** [mvantellingen/localshop#128]
Hi!

I have pip configured to hit my local localshop installation as the global default, and it seems like it's not caching the source tarball distribution when there's also a wheel available for the same version of the same package.

I.E. the argparse wheel is already cached in localshop, but trying to grab the argparse source distribution returns: 
```
HTTP/1.1 302 FOUND
Server: nginx/1.6.2
Date: Sat, 07 Feb 2015 01:59:52 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Location: https://pypi.python.org/packages/source/a/argparse/argparse-1.3.0.tar.gz
```

**Comment by canassa** [comment]
I was not able to reproduce this problem. I did a `pip install argparse` on a clean localshop installation and it returned 302 on the first call and 200 on any subsequent call. Could you please provide more detailed instructions on how to reproduce this?

**Comment by fly** [comment]
nevermind, this appears to have been a problem with celery. Restarting celery workers resulted in packages getting cached as usual.
