### ISSUE TITLE
uploading packages to local mirror with new account in localshop get 403 forbidden.

### ISSUE THREAD

**Issue by hnxuruochen** [mvantellingen/localshop#133]
When I create a new account and give him all the permission, he still can't upload a local package to local mirror until I give him the superuser authority.
But after I canceled his superuser authority and all permission. He can still upload local packages to local mirror.

**Comment by canassa** [comment]
Have you created the CIDR? Try setting the "Require credentials" to false.

**Comment by canassa** [comment]
I am closing this for now. Feel free to reopen if you are still having problems.
