### ISSUE TITLE
Simple index fails with 500 error (0.6.1) - problem with template and url

### ISSUE THREAD

**Issue by Jafula** [mvantellingen/localshop#134]
Just updated to 0.6.1 and visiting /simple in the browser returns a 500 error.

Turning on debug mode pointed to an issue with the template simple_package_list.html and the url simple_detail.

To fix the second parameter version="" was removed from the url. The template below stopped the 500 error.

    <html><head><title>Simple Index</title></head><body>
    {% for package in packages %}
    <a href="{% url 'packages-simple:simple_detail' slug=package.name %}">{{ package.name }}</a><br />
    {% endfor %}
    </body></html>

**Comment by canassa** [comment]
This should be fixed now
