### ISSUE TITLE
How to follow docker instructions ?

### ISSUE THREAD

**Issue by stuaxo** [mvantellingen/localshop#179]
Instructions are below ... there is no docker.conf.py file,  or if there is I don't know where, should I be in some directory, I just checked everything out from git and this is confusing:

```
Install docker and docker-compose and then run:

cp docker.conf.py{.example,}
docker-compose build
docker-compose run localshop syncdb
docker-compose run localshop createsuperuser
docker-compose up

You should be able to see localshop running in http://docker-host:8000.
```

**Comment by glenfant** [comment]
Was about to file this issue when I found this ticket. Since there's no answer, @stuaxo did you find a workaround ?

**Comment by stuaxo** [comment]
Nope, sorry :-/

**Comment by glenfant** [comment]
@stuaxo OK, here's something that worked for me, but I'm a docker stuffs noob and perhaps I missed something:

```bash
docker-compose build
docker-compose start db
# Following command should prompt you for a superuser login/password too
docker-compose run web localshop syncdb
docker-compose run -u root web localshop collectstatic
# Run the beast
docker-compose up

# Play with it
firefox http://localhost:8000
```

@mvantellingen any though about this ?

**Comment by stuaxo** [comment]
I tried this, the first command worked, but I got stuck on the 2nd command:

```
$ docker-compose start db
Starting db ... done
ERROR: No containers to start
```

**Comment by glenfant** [comment]
You must cd into the directory that contains "docker-compose.yml" first
After "docker-compose build" (may take a couple of minutes) you should see the 3 images with "docker images" command:

"localshop_db", "localshop_web" and "localshop_worker"

But again, I'm a Docker noob and @mvantellingen should provide a better answer.

**Comment by stuaxo** [comment]
I'm in the directory.

0docker images shows localshop_web and localshop_worker, but no localshop_db.
