### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by sposs** [mvantellingen/localshop#192]
Hi,
I'm wondering if this package is still maintained... I see the last changes are over a year ago. I know it works mostly, but I believe it could benefit from a django version upgrade. Moreover, python3 support seems not to be ok... I really like this tool (I highly depend on it) and I'd be annoyed if I had to change to something else... 
Thanks!

**Comment by sposs** [comment]
It appears this repo is sadly dead.

**Comment by canassa** [comment]
Hey @sposs 

I would also like to revive it a little bit, but I am unfortunately very busy with other projects. I tried to convince my current employer to adopt it so I could also invest some time on it, but they preferred to hire a third-party tool 😢 

I will see if I can spare some time to modernize it a little bit. I would appreciate any contribution.
