### ISSUE TITLE
Avoid package overwrite

### ISSUE THREAD

**Issue by lovato** [mvantellingen/localshop#61]
IMHO, i think if you submited a package to a broker like Localshop, I never can would be able to overwrite it, since it carries the sabe package version.

- upload package
- user installs it
- upload new package, same version

Now we face inconsistency. I fixed that on my simplepypi install by removing write permissions of the upload file. So, once uploaded, its uploaded.

About the other issue asking the ability to remove packages, we may go into this same inconsistency: if you remove, and then upload again? How to control that nobody already have it installed?

Best
Marco

**Comment by canassa** [comment]
We added support to disable package package overwrites via the [LOCALSHOP_RELEASE_OVERWRITE](http://localshop.readthedocs.org/en/latest/settings.html#localshop-release-overwrite) config.
