### ISSUE TITLE
Need a way to purge old development packages

### ISSUE THREAD

**Issue by rassie** [mvantellingen/localshop#8]
I'm uploading every SVN revision of our product to our localshop instance. However, we are both quite big a package and also quite restricted in terms of hard drive space. There is also absolutely no need to keep development packages older than a week. Therefore, I'd need a way to purge development packages (with version numbers like '1.2.dev-r1234'), either automatically via Celery or with a management command.

**Comment by canassa** [comment]
Closing. #36 duplication
