### ISSUE TITLE
AuthProfile is not automatically created, /accounts/username/edit/ raises 404

### ISSUE THREAD

**Issue by trbs** [mvantellingen/localshop#88]
It seems that AuthProfile is not automatically created when a user is created.

Because of this /accounts/username/edit/ raises 404

Workaround:
```python
def create_auth_profile(sender, **kwargs):
    user = kwargs['instance']
    if kwargs['created']:
        AuthProfile(user=user).save()

post_save.connect(create_auth_profile, sender=User, dispatch_uid="create_auth_profile")
```

**Comment by mvantellingen** [comment]
I've removed django-userena since it provided more features then we required. So this should be fixed now
