### ISSUE TITLE
unable to use local package uploads

### ISSUE THREAD

**Issue by joekimmel** [mvantellingen/localshop#98]
Hi, 
 i'm using localshop 1.4.3 installed per the instructions.

I'm able to install packages via my localshop server per the instructions (or by setting an environment variable PIP_INDEX_URL , but i mean same thing right? probly). 

However i'm trying to upload a fork of gunicorn, where i've bumped the major version to 180,  to my localshop server, and that fails in one of two ways depending on my .pypirc configuration file.

method 1, the documented method:
pypirc = 
[distutils]
index-servers =
  internal

[internal]
repository: http://10.77.0.5/simple/
username: 2cebb3ed0e6249de947a20e328a43dd5
password: 438c5415b8944beab6027366f89981a8

$python setup.py sdist upload -r internal
<...>
running upload
Submitting dist/gunicorn-180.2.tar.gz to http://10.77.0.5/simple/
Upload failed (400): BAD REQUEST

i look at my server logs and i can see nginx has returned the 400, but there's nothing in the localshop or celery logs indicating what the problem was. 

method 2:  i saw it on some blog post?
pypirc file is same as in option1, except the repository URL has been stripped of its "/simple", ie:
repository: http://10.77.0.5/

$python setup.py sdist upload -r internal
<...>
running upload
Submitting dist/gunicorn-180.2.tar.gz to http://10.77.0.5/
Server response (200): OK

but!! i don't see gunicorn-180.2  in my localshop packages list!! 

in either case when i try to install gunicorn through my localshop, it can see the main pypi versions but never my fork.  

I've also tried having the user credentials be those of the django super-user, but no luck there either.

so this is a shame as i was really hoping to use localshop to cache all packages and serve some internal packages,  but i can't figure out what's going wrong here.

**Comment by canassa** [comment]
You must rename the egg in case you want to upload a forked package, that's how PyPI works. One notable example of this pratice is [suds-jurko](https://pypi.python.org/pypi/suds-jurko) which is a fork of long time dead [suds](https://pypi.python.org/pypi/suds).

I am closing this issue as a "Won't fix"
